Gonzales/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('products/', views.products, name="products"),
    path('about/', views.about, name="about"),
    path('order/', views.order, name="order"),
    path('addProduct/', views.addProduct, name="addProduct"),
    path('editProduct/<int:pk>/', views.editProduct, name="editProduct"),
    path('deleteProduct/<int:pk>/', views.deleteProduct, name="deleteProduct"),
    path('addOrder/', views.addOrder, name="addOrder"),
    path('editOrder/<int:pk>/', views.editOrder, name="editOrder"),
    path('deleteOrder/<int:pk>/', views.deleteOrder, name="deleteOrder"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
# models.py

from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(default="No description available.")
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

class ProductTag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    reviewer_name = models.CharField(max_length=255)
    comment = models.TextField()
    rating = models.IntegerField()

    def __str__(self):
        return f"{self.product} - {self.reviewer_name}"

class OrderItem(models.Model):
    customerName = models.CharField(max_length=255, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.customerName} - {self.product} - {self.quantity}"

webapp/forms.py
from django.forms import ModelForm, forms
from .models import Product, OrderItem

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class OrderForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'


webapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import ProductForm, OrderForm

def homepage(request):
    return render(request, 'pages/homepage.html')

def products(request):
    product = Product.objects.all()
    return render(request, 'pages/products.html', {'product': product})

def about(request):
    return render(request, 'pages/about.html')

def order(request):
    order = OrderItem.objects.all()
    return render(request, 'pages/order.html', {'order':order})

def addOrder(request):
    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('order')
    context = {
        'form':form
    }
    return render(request, 'pages/addOrder.html', context)

def editOrder(request, pk):
    order = OrderItem.objects.get(id=pk)
    form = OrderForm(instance=order)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
    if form.is_valid():
        form.save()
        return redirect('order')
    context = {
        'form':form
    }
    return render(request, 'pages/editOrder.html', context)

def deleteOrder(request, pk):
    order = OrderItem.objects.get(id=pk)
    if request.method == 'POST':
        order.delete()
        return redirect('order')
    context = {
        'order':order
    }
    return render(request, 'pages/deleteOrder.html', context)

def addProduct(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('products')
    context = {
        'form':form
    }
    return render(request, 'pages/addProduct.html', context)



def editProduct(request, pk):
    product = Product.objects.get(id=pk)
    form = ProductForm(instance=product)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
    if form.is_valid():
        form.save()
        return redirect('products')
    context = {
        'form':form
    }
    return render(request, 'pages/editProduct.html', context)

def deleteProduct(request, pk):
    product = Product.objects.get(id=pk)

    if request.method == 'POST':
        product.delete()
        return redirect('products')
    context = {
        'product':product
    }
    return render(request, 'pages/deleteProduct.html', context)





webapp/templates/pages/about.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<section class="grids">
    <div class="contents">
        <div class="content-lefts">
            <div class="infos">
                <h2>About Us</h2>
                <p>Welcome to our enchanting world of baby wonders! At KiddiES, we celebrate the magic of infancy by curating a
                    delightful collection of products designed to cater to the unique needs of your little ones. Nestled in the heart
                    of Bacoor, Cavite, our baby shop is a haven for parents and caregivers seeking not only the
                    finest quality essentials but also a touch of whimsy and charm for their bundles of joy.</p>
                <p>Visit us at Soldiers Hill IV Bacoor, Cavite and explore a world where every tiny sock, every snug onesie,
                    and every gentle rattle tells a story of love, care, and the pure joy of parenthood.
                    Welcome to a world of endless possibilities for your little one at KiddiES –
                    where the magic of infancy comes to life!</p>


            </div>
        </div>
        <div class="content-right">
            <img src="{% static '/images/logo2.png' %}" alt="logo">
        </div>
    </div>
</section>
{% endblock %}

webapp/templates/pages/addOrder.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
    <div class="addProd">
        <button class="addButt"><a href="{% url 'order' %}" id="addSub">Back</a></button>
    </div>
<br>

     <h2>
        Add Order
     </h2>
<br>

<div class="container">
      <form action="" method="POST">
         {% csrf_token %}
          {{form}}


         <button type="submit">Add Order</button>
      </form>
</div>

{% endblock %}


webapp/templates/pages/addProduct.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
    <div class="addProd">
        <button class="addButt"><a href="{% url 'products' %}" id="addSub">Back</a></button>
    </div>
<br>

     <h2>
        Add Product
     </h2>
<br>

<div class="container">
      <form action="" method="POST">
         {% csrf_token %}
          <label>Product Name:</label>
          {{ form.name }}
          <label>Description:</label>
          {{ form.description }}
          <label>Price:</label>
          {{ form.price }}



         <button type="submit">Add Product</button>
      </form>
</div>

{% endblock %}

webapp/templates/pages/deleteOrder.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<div class="del">
     <h2>
        Delete Order
     </h2>
<br>

<p class="deleteMessage">Are you sure you want to delete this order {{order.product}} of  {{order.customerName}}?</p>

      <form action="" method="POST">
         {% csrf_token %}

          <div class="buttonsDel">
              <button type="submit" name="submit">Yes</button>
              <button><a href="{% url 'order' %}">Cancel</a></button>
          </div>

      </form>
</div>


{% endblock %}

webapp/templates/pages/deleteProduct.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<div class="del">
     <h2>
        Delete Product
     </h2>
<br>

<p class="deleteMessage">Are you sure you want to delete this product {{product}}?</p>

      <form action="" method="POST">
         {% csrf_token %}

          <div class="buttonsDel">
              <button type="submit" name="submit">Yes</button>
              <button><a href="{% url 'products' %}">Cancel</a></button>
          </div>

      </form>
</div>


{% endblock %}


webapp/templates/pages/editOrder.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
    <div class="addProd">
        <button class="addButt"><a href="{% url 'order' %}" id="addSub">Back</a></button>
    </div>
<br>

     <h2>
        Edit Order
     </h2>
<br>

<div class="container">
      <form action="" method="POST">
         {% csrf_token %}
          {{form}}



         <button type="submit">Save Changes</button>
      </form>
</div>

{% endblock %}

webapp/templates/pages/editProduct.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
    <div class="addProd">
        <button class="addButt"><a href="{% url 'products' %}" id="addSub">Back</a></button>
    </div>
<br>

     <h2>
        Edit Product
     </h2>
<br>

<div class="container">
      <form action="" method="POST">
         {% csrf_token %}
          {{form}}



         <button type="submit">Save Changes</button>
      </form>
</div>

{% endblock %}


webapp/templates/pages/homepage.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<section class="grid">
    <div class="content">
        <div class="content-left">
            <div class="info">
                <h2>Order For Your <br>Little Kiddo</h2>
                <p>Tiny wonders, endless possibilities. Explore a world of comfort and <br>cuteness with our curated collection of baby essentials. <br>
                    From snug onesies to adorable accessories,
                    we've got everything your little <br>bundle of joy needs for a happy and stylish start in life.</p>


            </div>
        </div>
        <div class="content-right">
            <img src="{% static '/images/baby.png' %}" alt="logo">
        </div>
    </div>
</section>
{% endblock %}

webapp/templates/pages/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ordering System</title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %} ">
    <link rel="icon" type="images/x-icon" href="{% static '/images/icon-baby.png' %}">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link href="fonts/css/font-awesome.min.css" rel="stylesheet">

</head>
<body>
{% include 'pages/navigation.html' %}
{% block content %}

{% endblock %}


<script src="{% static '/js/script.js' %}"></script>

</body>
</html>

webapp/templates/pages/menu.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<section class="category">
    <div class="list-items">
        <h3>Popular Products</h3>
        <div class="card-list">
            <div class="card">
                <img src="{% static '/images/baby wipes.jpeg' %}" alt="logo">
                <div class="prod-title">
                    <h1>Baby Wipes</h1>
                </div>
                <div class="price">
                    <span>₱ 250</span><span><i id="p2" onclick="myFunction1()" class="icon-plus-sign-alt"></i></span>
                </div>
            </div>

            <div class="card">
                <img src="{% static '/images/bottle.jpeg' %}" alt="logo">
                <div class="prod-title">
                    <h1>Bottle</h1>
                </div>
                <div class="price">
                    <span>₱ 150</span><span><i id="p1" onclick="myFunction()" class="icon-plus-sign-alt"></i></span>
                </div>
            </div>

            <div class="card">
                <img src="{% static '/images/baby wipes.jpeg' %}" alt="logo">
                <div class="prod-title">
                    <h1>Abott Wipes</h1>
                </div>
                <div class="price">
                    <span>₱ 350</span><span><i id="p3" onclick="myFunction3()" class="icon-plus-sign-alt"></i></span>
                </div>
            </div>

            <div class="card">
                <img src="{% static '/images/bottle2.jpeg' %}" alt="logo">
                <div class="prod-title">
                    <h1>Js Bottle</h1>
                </div>
                <div class="price">
                    <span>₱ 200</span><span><i id="p4" onclick="myFunction4()" class="icon-plus-sign-alt"></i></span>
                </div>
            </div>

            <div class="card">
                <img src="{% static '/images/diaper.jpeg' %}" alt="logo">
                <div class="prod-title">
                    <h1>Pampers</h1>
                </div>
                <div class="price">
                    <span>₱ 350</span><span><i id="p5" onclick="myFunction5()" class="icon-plus-sign-alt"></i></span>
                </div>
            </div>

            <div class="card">
                <img src="{% static '/images/jacket.jpeg' %}" alt="logo">
                <div class="prod-title">
                    <h1>Baby Jacket</h1>
                </div>
                <div class="price">
                    <span>₱ 450</span><span><i id="p6" onclick="myFunction6()" class="icon-plus-sign-alt"></i></span>
                </div>
            </div>

            <div class="card">
                <img src="{% static '/images/shoes1.jpeg' %}" alt="logo">
                <div class="prod-title">
                    <h1>Baby Shoes</h1>
                </div>
                <div class="price">
                    <span>₱ 550</span><span><i id="p7" onclick="myFunction7()" class="icon-plus-sign-alt"></i></span>
                </div>
            </div>

            <div class="card">
                <img src="{% static '/images/shoes2.jpeg' %}" alt="logo">
                <div class="prod-title">
                    <h1>Baby Shoes</h1>
                </div>
                <div class="price">
                    <span>₱ 650</span><span><i id="p8" onclick="myFunction8()" class="icon-plus-sign-alt"></i></span>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

webapp/templates/pages/navigation.html
{% load static %}

{% block content %}
<section class="menu">
    <div class="nav">
        <div class="logo"><h1>Kiddi<b>ES</b></h1></div>
        <ul>
            <li><a href="{% url 'homepage' %}">Home</a></li>
            <li><a href="{% url 'products' %}">Products</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'order' %}">Orders</a></li>

        </ul>

    </div>
</section>


{% endblock %}

webapp/templates/pages/order.html
{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<br>
<div class="addProd">
<button class="addButt"><a href="{% url 'addOrder' %}" class="add-button">Add Order</a></button>
</div>
<div class="table-responsive">
    <table>
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Image</th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for order in order %}
                <td>{{order.customerName}}</td>
                <td>
                    <img src="{% static '/images/book_image.jpg' %}" alt="logo">
                </td>
                <td>{{order.product}}</td>
                <td>{{order.price}}</td>
                <td>{{order.quantity}}</td>
                <td>
                    <span class="action-btn">
                        <a id="order" href="{% url 'editOrder' order.id %}">Edit</a>
                        <a id="re1" href="{% url 'deleteOrder' order.id %}">Remove</a>
                    </span>
                </td>
            </tr>
        {% endfor %}


        </tbody>
    </table>
</div>
{% endblock %}

webapp/templates/pages/products.html
<!-- products.html -->

{% extends 'pages/index.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<br>
<div class="addProd">
<button class="addButt"><a href="{% url 'addProduct' %}" class="add-button">Add Product</a></button>
</div>
<br>
<br>

<div class="product-list">
   {% for product in product %}
       <div class="product">
           <h2>{{ product.name }}</h2>
            <br>
           <img src="{% static '/images/book_image.jpg' %}" alt="" style="height: 150px; width: 150px;">
           <p>{{ product.description }}</p>
           <p>Price: ₱{{ product.price }}</p>
           <p>Rating: {% for _ in product.productreview_set.all %}★{% endfor %} ({{ product.productreview_set.count }} reviews)</p>
           <ul>
               {% for review in product.productreview_set.all %}
                   <li>
                       <strong>{{ review.reviewer_name }}</strong> - {{ review.comment }} (Rating: {{ review.rating }}★)
                   </li>
               {% endfor %}
           </ul>

           <div class="editDel">
            <button class="editButt"><a href="{% url 'editProduct' product.id %}" class="add-button">Edit Product</a></button>
            <button class="delButt"><a href="{% url 'deleteProduct' product.id %}" class="add-button">Delete Product</a></button>
           </div>
       </div>
   {% endfor %}
</div>
{% endblock %}